#!/bin/csh
#PBS -N MyJobName
#PBS -l select=1:ncpus=N:mem=2GB
#PBS -l walltime=10:00:00
#PBS -m ea
#PBS –M username@uni.sydney.edu.au
#PBS -V
cd "$PBS_O_WORKDIR"
module load Matlab2019b
matlab -nodisplay -singleCompThread -r "yourMatlabScript, exit"
